version: '3'

services:
  # 自动化后端：负责 Git + Hexo 编译 + Webhook
  hexo-auto:
    build: .
    container_name: hexo_auto
    network_mode: host
    volumes:
      - .:/blog
      - /root/.ssh:/root/.ssh:ro
    environment:
      - NODE_ENV=production
      - HTTP_PROXY=http://127.0.0.1:7890
      - HTTPS_PROXY=http://127.0.0.1:7890
    restart: always